services:

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observer_network


  alembic:
    build: .
    command: alembic upgrade head  
    volumes:
      - .:/app
    networks:
      - observer_network


  celery:
    build: .
    command: >
      celery -A celery_worker:celery worker --pool=eventlet -l info -E

    environment:
      - REDIS_URL=redis://redis:6379/0
      - TEMP_DIR=/shared_temp
    depends_on:    
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - observer_network

  flower:
    build: .
    command: >
      celery --broker=redis://redis:6379/0 flower --address=0.0.0.0 --port=5555 --inspect-timeout=10

    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery
    volumes:
      - .:/app
    networks:
      - observer_network

  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - celery
      - alembic
    volumes:
      - .:/app
      - ./shared_temp:/shared_temp
    command: gunicorn -c gunicorn.conf.py --worker-class eventlet --workers 2 --worker-connections 1000 run:app

    networks:
      - observer_network


networks:
  observer_network:
    external: true
