services:
  alembic:
    build: .
    command: alembic upgrade head      
    volumes:
      - .:/app
    networks:
      - observer${ENV}_network


  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - alembic
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - observer${ENV}_network

  init_password:
    build: .
    command: python password.py  # Запуск скрипта для добавления админа
    depends_on:
      - alembic
    networks:
      - observer${ENV}_network
    volumes:
      - .:/app



networks:
  observer${ENV}_network:
    external: true
