services:
  alembic:
    build: .
    command: alembic upgrade head      
    volumes:
      - .:/app
    networks:
      - observer_network

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - observer_network


  celery:
    build: .
    command: >
      celery -A celery_worker:celery worker -l info -E
    environment:
      - REDIS_URL=redis://redis:${REDIS_PORT}/0

    depends_on:    
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - observer_network

  flower:
    build: .
    command: celery -A celery_worker flower --address=0.0.0.0 --port=5555 --broker=redis://redis:${REDIS_PORT}
    ports:
      - "${FLOWER_PORT}:5555"
    environment:
      - REDIS_URL=redis://redis:${REDIS_PORT}/0
    depends_on:
      - redis
      - celery
    volumes:
      - .:/app
    networks:
      - observer_network


  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
      - HTTP_PROXY=
      - HTTPS_PROXY=
    depends_on:
      - alembic
      - celery
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py --worker-class eventlet -w 1 run:app
    networks:
      - observer_network


networks:
  observer_network:
    external: true
