services:
  alembic:
    build: .
    command: alembic upgrade head      
    volumes:
      - .:/app
    networks:
      - observer_network


  web:
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      - alembic
    volumes:
      - .:/app
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - observer_network

  init_password:
    build: .
    command: python password.py  # Запуск скрипта для добавления админа
    depends_on:
      - alembic
    networks:
      - observer_network
    volumes:
      - .:/app



networks:
  observer_network:
    external: true
