services:
  alembic:
    build: .
    command: alembic upgrade head
    volumes:
      - .:/app
    networks:
      - observer_network

  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      - alembic
    volumes:
      - .:/app
      - ./shared_temp:/shared_temp
    command: >
       gunicorn -c gunicorn.conf.py --bind 0.0.0.0:${FLASK_PORT} run:app
    networks:
      - observer_network



networks:
  observer_network:
    driver: bridge
